on:
  workflow_dispatch:

name: Update Data / Redeploy App

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install specific packages
        run: |
          install.packages(c("httr", "rStrava", "aws.s3"))
        shell: Rscript {0}
