on:
  workflow_dispatch:

name: Update Data / Redeploy App

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          lockfile-create-lib: '.libPaths()[1]'
          extra-packages: |
            any::httr
            any::rStrava
            any::aws.s3

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import / wrangle / save data to s3
        env:
          STRAVA_KEY: ${{ secrets.STRAVA_KEY }}
          STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: Rscript R/scrape_strava.R






