on:
  workflow-dispatch:

name: Update Data / Redeploy App

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::shiny
            any::shinydashboard
            any::shinyWidgets
            any::shinycssloaders
            any::tidyverse
            any::plotly
            any::DT
            any::leaflet
            any::leaflet.extras
            any::htmlwidgets
            any::htmltools
            any::fontawesome
            any::markdown
            any::fresh
            any::aws.s3
            any::rsconnect

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Import / wrangle / save data to s3
         env:
          STRAVA_KEY: ${{ secrets.STRAVA_KEY }}
          STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: Rscript R/scrape_strava.R






